# SPDX-License-Identifier: GPL-3.0-only
---
<<<<<<< HEAD
# defaults file for roles/proxmox_vm_template


# IP Addresses for VM's in Proxmox

pve_vm_network: 192.168.0.0

pve_vm_gw: 192.168.0.1

pve_vm_dns: 192.168.0.150

pve_vm_mariadb: 192.168.0.151

pve_vm_httpd: 192.168.0.152

pve_vm_nginx: 192.168.0.153


# Configurations for Proxmox VMs.
pve_vm_vms:
  - name: 'Rocky-FreeIPA01'
    vmid: 150
    ip: "{{ pve_vm_dns }}"
    cores: 2
    memory: 4096
    nameserver:
      - "{{ pve_vm_dns }}"
      - '1.1.1.1'

  - name: 'Rocky-MariaDB01'
    vmid: 151
    ip: "{{ pve_vm_mariadb }}"
    cores: 4
    memory: 8192
    nameserver:
      - "{{ pve_vm_dns }}"
      - '1.1.1.1'

  - name: 'Rocky-Apache01'
    vmid: 152
    ip: "{{ pve_vm_httpd }}"
    cores: 2
    memory: 4096
    nameserver:
      - "{{ pve_vm_dns }}"
      - '1.1.1.1'

  - name: 'Rocky-nginx01'
    vmid: 153
    ip: "{{ pve_vm_nginx }}"
    cores: 2
    memory: 4096
    nameserver:
      - "{{ pve_vm_dns }}"
      - '1.1.1.1'
=======
# All VM configuration is defined in group_vars/all.yml and group_vars/pve_vm.yml
>>>>>>> 037f876fe6c40c647f38f7f55fcb8576c3ebd03c
