# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/binddns
- name: Update packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  tags:
    - skip_ansible_lint

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - bind
      - bind-utils
      - firewalld
      - python3-firewall
    state: present

- name: Backup and configure_named.conf
  ansible.builtin.template:
    src: named.conf.j2
    dest: "{{ binddns_bind_conf_path }}"
    mode: '0640'
    backup: true
    group: named
    owner: named
  notify: Restart_named

- name: Create forward zone
  ansible.builtin.template:
    src: forward-zone.j2
    dest: "{{ binddns_bind_zone_dir }}/{{ binddns_dns_domain }}.db"
    mode: '0644'
    group: named
    owner: named
  notify: Restart_named

- name: Create reverse zone
  ansible.builtin.template:
    src: reverse-zone.j2
    dest: "{{ binddns_bind_zone_dir }}/{{ binddns_dns_domain }}.rev"
    mode: '0644'
    group: named
    owner: named
  notify: Restart_named

- name: Add LAMP VMs to forward DNS zone
  ansible.builtin.lineinfile:
    path: "{{ binddns_bind_zone_dir }}/{{ binddns_dns_domain }}.db"
    insertafter: ';A Record for IP address to Hostname'
    line: "{{ item.name | lower }} IN A {{ item.ip }}"
  loop: "{{ pve_vm_vms }}"
  notify: Restart_named

- name: Add LAMP VMs to reverse DNS zone
  ansible.builtin.lineinfile:
    path: "{{ binddns_bind_zone_dir }}/{{ binddns_dns_domain }}.rev"
    insertafter: ";PTR Record IP address to HostName"
    line: "{{ item.ip.split('.')[-1] }} IN PTR {{ item.name | lower }}.{{ binddns_dns_domain }}."
  loop: "{{ pve_vm_vms }}"
  notify: Restart_named

- name: Open DNS ports in firewall
  ansible.posix.firewalld:
    service: dns
    permanent: true
    state: enabled
    immediate: true
  notify: Reload_firewalld
