# SPDX-License-Identifier: MIT-0
---
# defaults file for roles/nginx

nginx_ca_passphrase: Kode1234!

# The upstream backend IP nginx will proxy_pass to
nginx_upstream_ip: "{{ pve_ip_httpd }}"

# The DNS resolver nginx should use for dynamic upstreams
nginx_resolver_ip: "{{ pve_ip_dns }}"

# Ports
nginx_http_port: 80
nginx_https_port: 443
