
# Domain Configuration
binddns_dns_domain: "domain.example"
binddns_dns_reverse_zone: "0.168.192.in-addr.arpa"
binddns_dns_network: "192.168.0.0"

# DNS Service name
binddns_bind_service: "named"

# Bind paths
binddns_bind_conf_path: /etc/named.conf
binddns_bind_zone_dir: /var/named
binddns_bind_log_dir: /var/log/named

# Forwarders
binddns_dns_forwarders_primary: "1.1.1.1"
binddns_dns_forwarders_secondary: "1.0.0.1"

# Recursion
binddns_dns_recursion: true

# Zone file serial (YYYYMMDDNN format)
binddns_dns_serial: "{{ ansible_facts['date_time']['date'] | replace('-', '') }}01"

# SOA record details
binddns_dns_soa_refresh: 3600
binddns_dns_soa_retry: 1800
binddns_dns_soa_expire: 604800
binddns_dns_soa_minimum: 86400
