---
# ============================================================
# LAMP Stack VM configurations
# ============================================================

# ____ Configurations for Proxmox VMs ____
pve_vm_vms:
  - name: 'Rocky-DNS01'
    vmid: 200
    ip: "{{ pve_ip_dns }}"
    cpu: x86-64-v3
    cores: 2
    memory: 4096
    nameserver:
      - "{{ pve_ip_dns }}"
      - '1.1.1.1'

  - name: 'Rocky-MariaDB01'
    vmid: 201
    ip: "{{ pve_ip_mariadb }}"
    cpu: x86-64-v3
    cores: 4
    memory: 8192
    nameserver:
      - "{{ pve_ip_dns }}"
      - '1.1.1.1'

  - name: 'Rocky-Apache01'
    vmid: 202
    ip: "{{ pve_ip_httpd }}"
    cpu: x86-64-v3
    cores: 2
    memory: 4096
    nameserver:
      - "{{ pve_ip_dns }}"
      - '1.1.1.1'

  - name: 'Rocky-Nginx01'
    vmid: 203
    ip: "{{ pve_ip_nginx }}"
    cpu: x86-64-v3
    cores: 2
    memory: 4096
    nameserver:
      - "{{ pve_ip_dns }}"
      - '1.1.1.1'
