# IP Addresses for VM's in Proxmox

pve_vm_network: 192.168.0.0

pve_vm_gw: 192.168.0.1

pve_vm_dns: 192.168.0.150

pve_vm_mariadb: 192.168.0.151

pve_vm_httpd: 192.168.0.152

pve_vm_nginx: 192.168.0.153


# Configurations for Proxmox VMs.
pve_vm_vms:
  - name: 'Rocky-DNS01'
    vmid: 102
    ip: "{{ pve_vm_dns }}"
    cores: 2
    memory: 4096
    nameserver:
      - "{{ pve_vm_dns }}"
      - '1.1.1.1'

  - name: 'Rocky-MariaDB01'
    vmid: 103
    ip: "{{ pve_vm_mariadb }}"
    cores: 4
    memory: 8192
    nameserver:
      - "{{ pve_vm_dns }}"
      - '1.1.1.1'

  - name: 'Rocky-Apache01'
    vmid: 104
    ip: "{{ pve_vm_httpd }}"
    cores: 2
    memory: 4096
    nameserver:
      - "{{ pve_vm_dns }}"
      - '1.1.1.1'

  - name: 'Rocky-nginx01'
    vmid: 105
    ip: "{{ pve_vm_nginx }}"
    cores: 2
    memory: 4096
    nameserver:
      - "{{ pve_vm_dns }}"
      - '1.1.1.1'
