# SPDX-License-Identifier: MIT-0
---
# handlers file for roles/mariadb
<<<<<<< HEAD

- name: Reload_DB
  ansible.builtin.systemd:
    name: mariadb
    state: started
    enabled: true

- name: Reload_firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
# Allow mysql in firewall

=======
>>>>>>> 037f876fe6c40c647f38f7f55fcb8576c3ebd03c
