# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/proxmox_vm_template

- name: Create new VM using cloud-init with a username and password
  community.proxmox.proxmox_kvm:
    node: pve
    api_user: root@pam
    api_password: "{{ all_pw }}"
    api_host: 10.101.8.107
    agent: true
    name: "{{ item.name }}"
    vmid: "{{ item.vmid }}"
    cpu: x86-64-v3
    cores: "{{ item.cores }}"
    memory: "{{ item.memory }}"
    scsihw: virtio-scsi-pci
    # Use .qcow2 image for cloud-init
    scsi:
      scsi0: 'local-lvm:0,import-from=/root/Rocky-10-GenericCloud-Base.latest.x86_64.qcow2'
    ide:
      ide2: 'local-lvm:cloudinit'
    ciuser: rocky
    cipassword: "{{ all_pw }}"
    # Use ansible controller SSH keys
    sshkeys: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    searchdomains: 'domain.local'
    nameservers: "{{ item.nameserver }}"
    net:
      net0: 'virtio,bridge=vmbr1'
    ipconfig:
      ipconfig0: 'ip={{ item.ip }}/24,gw={{ pve_vm_gw }}'
  # Run modules with ansible controller, instead of installing on PVE host
  delegate_to: localhost
  loop: "{{ pve_vm_vms }}"

- name: Start the VM
  community.proxmox.proxmox_kvm:
    api_user: root@pam
    api_password: "{{ all_pw }}"
    api_host: 10.101.8.107
    vmid: "{{ item.vmid }}"
    state: started
  delegate_to: localhost
  loop: "{{ pve_vm_vms }}"

- name: Wait for VM to be reachable
  ansible.builtin.wait_for:
    host: "{{ item.ip }}"
    port: 22
    delay: 10
    timeout: 60
  delegate_to: localhost
  loop: "{{ pve_vm_vms }}"

- name: Set Danish keyboard layout
  ansible.builtin.command: localectl set-keymap dk
  delegate_to: "{{ item.ip }}"
  become: true
  loop: "{{ pve_vm_vms }}"
  vars:
    ansible_user: rocky
  tags: skip_ansible_lint

- name: Set Danish keyboard layout
  ansible.builtin.command: timedatectl set-timezone Europe/Copenhagen
  delegate_to: "{{ item.ip }}"
  become: true
  loop: "{{ pve_vm_vms }}"
  vars:
    ansible_user: rocky
  tags: skip_ansible_lint

- name: Add rocky to sudo wheel
  ansible.builtin.user:
    name: rocky
    groups: wheel
    append: true
  delegate_to: "{{ item.ip }}"
  become: true
  loop: "{{ pve_vm_vms }}"
  vars:
    ansible_user: rocky

- name: Install packages not included in cloud image (Firewalld, zip, vim)
  ansible.builtin.dnf:
    name:
      - epel-release
      - firewalld
      - zip
      - vim
      - git
      - bash-completion
      - wget
    state: present
  delegate_to: "{{ item.ip }}"
  loop: "{{ pve_vm_vms }}"
  become: true
  vars:
    ansible_user: rocky
  notify:
    Firewalld_start

- name: Install freeipa-client
  ansible.builtin.dnf:
    name:
      - ipa-client
    state: present
  delegate_to: "{{ item.ip }}"
  become: true
  loop: "{{ pve_vm_vms }}"
  when: item.name != 'Rocky-FreeIPA01'
  vars:
    ansible_user: rocky

- name: Require password for sudo (remove NOPASSWD for wheel group)
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^%wheel\s+ALL=\(ALL\)\s+NOPASSWD:\s+ALL'
    line: '%wheel  ALL=(ALL)       ALL'
    validate: '/usr/sbin/visudo -cf %s'
  delegate_to: "{{ item.ip }}"
  become: true
  loop: "{{ pve_vm_vms }}"
  vars:
    ansible_user: rocky

- name: Remove cloud-init sudoers file if it exists
  ansible.builtin.file:
    path: /etc/sudoers.d/90-cloud-init-users
    state: absent
  delegate_to: "{{ item.ip }}"
  become: true
  loop: "{{ pve_vm_vms }}"
  vars:
    ansible_user: rocky
    ansible_become_pass: "{{ all_pw }}"
