# SPDX-License-Identifier: MIT-0
---
- name: Update packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  tags: skip_ansible_lint

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
  notify: Nginx_reload

- name: Start nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true

- name: Create nginx PKI directory
  ansible.builtin.file:
    path: /etc/pki/nginx
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create CA directory
  ansible.builtin.file:
    path: /etc/pki/CA/private
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Create CA private key
  community.crypto.openssl_privatekey:
    path: /etc/pki/CA/private/CA.key
    passphrase: "{{ nginx_ca_passphrase }}"
    cipher: auto

- name: Create CSR for CA certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: /etc/pki/CA/private/CA.key
    privatekey_passphrase: "{{ nginx_ca_passphrase }}"
    common_name: nginx CA
    use_common_name_for_san: false
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
  register: ca_csr

- name: Create self-signed CA certificate
  community.crypto.x509_certificate:
    path: /etc/pki/CA/private/CA.pem
    csr_content: "{{ ca_csr.csr }}"
    privatekey_path: /etc/pki/CA/private/CA.key
    privatekey_passphrase: "{{ nginx_ca_passphrase }}"
    provider: selfsigned

- name: Create private key for {{ nginx_domain_name }}
  community.crypto.openssl_privatekey:
    path: /etc/pki/nginx/{{ nginx_domain_name }}.key

- name: Create CSR for {{ nginx_domain_name }}
  community.crypto.openssl_csr_pipe:
    privatekey_path: /etc/pki/nginx/{{ nginx_domain_name }}.key
    subject_alt_name:
      - "DNS:{{ nginx_domain_name }}"
      - "IP:{{ nginx_upstream_ip }}"
  register: domain_csr

- name: Sign certificate for {{ nginx_domain_name }} with CA
  community.crypto.x509_certificate:
    path: /etc/pki/nginx/{{ nginx_domain_name }}.crt
    csr_content: "{{ domain_csr.csr }}"
    provider: ownca
    ownca_path: /etc/pki/CA/private/CA.pem
    ownca_privatekey_path: /etc/pki/CA/private/CA.key
    ownca_privatekey_passphrase: "{{ nginx_ca_passphrase }}"
    ownca_not_after: +365d
    ownca_not_before: "-1d"

- name: Create nginx configuration for {{ nginx_domain_name }}
  ansible.builtin.template:
    src: nginx_conf.j2
    dest: /etc/nginx/conf.d/{{ nginx_domain_name }}.conf
    owner: root
    group: root
    mode: '0644'
  notify: Nginx_restart

- name: Enable and start firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: Configure firewalld
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - http
    - https
  notify:
    - SELinux_httpd
    - Firewall_reload
