---
myhosts:
  hosts:
    # ubuntu-01:
    #     ansible_host: 10.101.36.253
    #     ansible_user: "{{ ubuntu_user }}"
    #     ansible_ssh_pass: "{{ all_pw }}"
    #     ansible_become_pass: "{{ all_pw }}"

    # ubuntu-02:
    #     ansible_host: 10.101.156.24
    #     ansible_user: "{{ ubuntu_user }}"
    #     ansible_ssh_pass: "{{ all_pw }}"
    #     ansible_become_pass: "{{ all_pw }}"

    Rocky-02:
        ansible_host: 10.101.103.218
        ansible_user: "{{ rocky_user }}"
        ansible_ssh_pass: "{{ all_pw }}"
        ansible_become_pass: "{{ all_pw }}"

dns_servers:
  hosts:
    Rocky-DNS01:
      ansible_host: 192.168.0.101
      ansible_user: rocky
      ansible_ssh_pass: "{{ all_pw }}"
      ansible_become_pass: "{{ all_pw }}"

webservers:
  hosts:
    Rocky-Apache01:
      ansible_host: 192.168.0.103
      ansible_user: rocky
      ansible_ssh_pass: "{{ all_pw }}"
      ansible_become_pass: "{{ all_pw }}"

dbservers:
  hosts:
    Rocky-MariaDB01:
      ansible_host: 192.168.0.102
      ansible_user: rocky
      ansible_ssh_pass: "{{ all_pw }}"
      ansible_become_pass: "{{ all_pw }}"

nginxservers:
  hosts:
    Rocky-Nginx01:
      ansible_host: 192.168.0.104
      ansible_user: rocky
      ansible_ssh_pass: "{{ all_pw }}"
      ansible_become_pass: "{{ all_pw }}"

proxmoxhosts:
  hosts:
    proxmox01:
      ansible_host: 10.101.8.107
      ansible_user: root
      ansible_ssh_pass: "{{ all_pw }}"
      ansible_become_pass: "{{ all_pw }}"
