---

dns_servers:
  hosts:
    Rocky-DNS01:
      ansible_host: 192.168.0.101
      ansible_user: rocky
      ansible_ssh_pass: "{{ default_password }}"
      ansible_become_pass: "{{ default_password }}"

webservers:
  hosts:
    Rocky-Apache01:
      ansible_host: 192.168.0.103
      ansible_user: rocky
      ansible_ssh_pass: "{{ default_password }}"
      ansible_become_pass: "{{ default_password }}"

dbservers:
  hosts:
    Rocky-MariaDB01:
      ansible_host: 192.168.0.102
      ansible_user: rocky
      ansible_ssh_pass: "{{ default_password }}"
      ansible_become_pass: "{{ default_password }}"

nginxservers:
  hosts:
    Rocky-Nginx01:
      ansible_host: 192.168.0.104
      ansible_user: rocky
      ansible_ssh_pass: "{{ default_password }}"
      ansible_become_pass: "{{ default_password }}"

proxmoxhosts:
  hosts:
    proxmox01:
      ansible_host: 10.101.8.107
      ansible_user: root
      ansible_ssh_pass: "{{ default_password }}"
      ansible_become_pass: "{{ default_password }}"
