---
myhosts:
  hosts:
    # ubuntu-01:
    #     ansible_host: 10.101.36.253
    #     ansible_user: "{{ ubuntu_user }}"
    #     ansible_ssh_pass: "{{ all_pw }}"
    #     ansible_become_pass: "{{ all_pw }}"

    # ubuntu-02:
    #     ansible_host: 10.101.156.24
    #     ansible_user: "{{ ubuntu_user }}"
    #     ansible_ssh_pass: "{{ all_pw }}"
    #     ansible_become_pass: "{{ all_pw }}"

    Rocky-02:
        ansible_host: 10.101.103.218
        ansible_user: "{{ rocky_user }}"
        ansible_ssh_pass: "{{ all_pw }}"
        ansible_become_pass: "{{ all_pw }}"

    # PROXMOX-HOST:
    #     ansible_host: 10.101.8.107
    #     ansible_user: jox
    #     ansible_ssh_pass: "{{ all_pw }}"

dns_servers:
  hosts:
      Rocky-Bind9:
        ansible_host: 192.168.0.116
        ansible_user: rocky
        ansible_ssh_pass: "{{ all_pw }}"
        ansible_become_pass: "{{ all_pw }}"

webservers:
  hosts:
      Rocky-WP01:
        ansible_host: 192.168.0.117
        ansible_user: rocky
        ansible_ssh_pass: "{{ all_pw }}"
        ansible_become_pass: "{{ all_pw }}"

dbservers:
  hosts:
      Rocky-DB01:
        ansible_host:
        ansible_user: rocky
        ansible_ssh_pass: "{{ all_pw }}"
        ansible_become_pass: "{{ all_pw }}"